### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by Benuhx** [lolouk44/xiaomi_mi_scale#39]
**Describe the bug**
mi-scale Version: 0.1.14

Container fails to start with the following exception:

```
2020-12-03 16:14:48 - Starting Xiaomi mi Scale...
2020-12-03 16:14:48 - Loading Config From OS Environment...
Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 28, in <module>
    with open('/data/options.json') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/options.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 165, in <module>
    if MQTT_DISCOVERY.lower() in ['true', '1', 'y', 'yes']:
AttributeError: 'bool' object has no attribute 'lower'
```

**To Reproduce**
Start mi-scale with the following docker-compose:

```
version: "3.5"
services:
   mi-scale:
      image: lolouk44/xiaomi-mi-scale:latest
      container_name: mi-scale
      restart: always
      depends_on:
        - mos
      network_mode: host
      privileged: true

      environment:
      - MISCALE_MAC=C4:27:9B:B6:AE:10
      - MQTT_HOST=127.0.0.1
      - MQTT_PREFIX=miScale
      - USER1_GT=70
      - USER1_SEX=male
      - USER1_NAME=Benuhx
      - USER1_HEIGHT=183
      - USER1_DOB=1990-01-01
```

Run `docker logs mi-scale` to display the exception

**Desktop/Server (please complete the following information):**
 Docker-compose with Raspberry pi 4 and built-in Bluetooth

**Additional Information:**
Seems to be the same issue as #31 but the bug is not fixed for me. I've double checked my mi-scale version, it is definitly the latest version 0.1.14 created 7 day ago:

`docker images` shows:

```
REPOSITORY                                       TAG                 IMAGE ID            CREATED             SIZE
lolouk44/xiaomi-mi-scale                   latest              ffe67ecaf549        7 days ago          318MB
```

**Comment by lolouk44** [comment]
Hi @Benuhx ,

Nice to see you again 😃 

You're missing some stuff in your docker-compose.
Please look at the [docker-compose](https://github.com/lolouk44/xiaomi_mi_scale#docker-compose) section and add the missing bits. Set them to `false` if you don't use them
I'll see if I can add a better handler for missing config bits

**Comment by Benuhx** [comment]
Hi @lolouk44 

thanks for your quick response 😀.

I've updated the enviroment section in the docker-compose. The container starts and the messages are published with MQTT 😁

For refererence my new docker-compose:

```
version: "3.5"
services:
    mi-scale:
      image: lolouk44/xiaomi-mi-scale:latest
      container_name: mi-scale
      restart: always
      depends_on:
        - mos
      network_mode: host
      privileged: true

      environment:
      - HCI_DEV=hci0
      - MISCALE_MAC=C4:27:9B:B6:AE:10
      - MQTT_HOST=127.0.0.1
      - MQTT_PORT=1883
      - MQTT_PREFIX=miScale
      - TIME_INTERVAL=30
      - MQTT_DISCOVERY=true
      - USER1_GT=70
      - USER1_SEX=male
      - USER1_NAME=Benuhx
      - USER1_HEIGHT=183
      - USER1_DOB=1990-01-01
```
