### ISSUE TITLE
Not sure what I'm doing wrong here

### ISSUE THREAD

**Issue by atv2016** [lolouk44/xiaomi_mi_scale#63]
Keep getting this:

```
mi-scale         | KeyError: 'options'
mi-scale         | TERM environment variable not set.
mi-scale         | Traceback (most recent call last):
mi-scale         |   File "/opt/miscale/Xiaomi_Scale.py", line 122, in <module>
mi-scale         |     data = json.load(json_file)["options"]
mi-scale         | KeyError: 'options'

```

My docker file is:

```

  mi-scale:
    image: lolouk44/xiaomi-mi-scale:latest
    container_name: mi-scale
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./mi-scale:/data
      - /var/run/dbus/:/var/run/dbus/:ro #needed for bleak
    
```

Been over and over on this but can't find out what's wrong. And the options.json file is there obviously.
